src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProjectRepository;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $started_at = null;

    #[ORM\ManyToOne(inversedBy: 'projects')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ProjectCategory $category = null;

    #[ORM\Column(length: 100)]
    private ?string $shortText = null;

    #[ORM\Column(length: 50)]
    private ?string $environment = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $link = null;

    #[ORM\Column(length: 255)]
    private ?string $icon = null;

    #[ORM\ManyToMany(targetEntity: Skill::class, inversedBy: 'projects')]
    private Collection $skill;

    #[ORM\Column]
    private ?bool $displayOnIndex = null;

    public function __construct()
    {
        $this->skill = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeImmutable
    {
        return $this->started_at;
    }

    public function setStartedAt(\DateTimeImmutable $started_at): self
    {
        $this->started_at = $started_at;

        return $this;
    }

    public function getCategory(): ?ProjectCategory
    {
        return $this->category;
    }

    public function setCategory(?ProjectCategory $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getShortText(): ?string
    {
        return $this->shortText;
    }

    public function setShortText(string $shortText): self
    {
        $this->shortText = $shortText;

        return $this;
    }

    public function getEnvironment(): ?string
    {
        return $this->environment;
    }

    public function setEnvironment(string $environment): self
    {
        $this->environment = $environment;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function setIcon(string $icon): self
    {
        $this->icon = $icon;

        return $this;
    }

    /**
     * @return Collection<int, Skill>
     */
    public function getSkill(): Collection
    {
        return $this->skill;
    }

    public function addSkill(Skill $skill): self
    {
        if (!$this->skill->contains($skill)) {
            $this->skill->add($skill);
        }

        return $this;
    }

    public function removeSkill(Skill $skill): self
    {
        $this->skill->removeElement($skill);

        return $this;
    }

    public function isDisplayOnIndex(): ?bool
    {
        return $this->displayOnIndex;
    }

    public function setDisplayOnIndex(bool $displayOnIndex): self
    {
        $this->displayOnIndex = $displayOnIndex;

        return $this;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Skill;
use App\Entity\Project;
use App\Entity\ProjectCategory;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\DBAL\Types\BooleanType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'attr' => [
                    'maxLength' => 80
                ]
            ])

            ->add('description', TextareaType::class, [
                'required' => false,
            ])

            ->add('started_at', DateType::class, [
                'widget' => 'single_text',
                'mapped' => false,
            ])

            ->add('shortText', TextType::class, [
                'attr' => [
                    'maxLength' => 50
                ]
            ])

            ->add('environment', TextType::class, [
                'attr' => [
                    'maxLength' => 50
                ]
            ])

            ->add('link', TextType::class, [
                'attr' => [
                    'maxLength' => 100,
                ]
            ])

            ->add('icon', TextType::class, [
                'attr' => [
                    'maxLength' => 255,
                ]
            ])

            ->add('category', EntityType::class, [
                'class' => ProjectCategory::class,
                'choice_label' => 'name',
            ])

            ->add('skill', EntityType::class, [
                'class' => Skill::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true,
            ])

            ->add('displayOnIndex')

            ->add('submit', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use DateTimeImmutable;
use App\Entity\Project;
use App\Form\ProjectType;
use App\Repository\ProjectRepository;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\ProjectCategoryRepository;
use DateTime;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/project', name: 'project')]
class ProjectController extends AbstractController
{
    private ProjectCategoryRepository $projectCategoryRepository;
    private ProjectRepository $projectRepository;
    private ManagerRegistry $managerRegistry;
    private SluggerInterface $slugger;

    public function __construct(
        ProjectCategoryRepository $projectCategoryRepository,
        ProjectRepository $projectRepository,
        ManagerRegistry $managerRegistry,
        SluggerInterface $slugger,
    ) {
        $this->projectCategoryRepository = $projectCategoryRepository;
        $this->projectRepository = $projectRepository;
        $this->managerRegistry = $managerRegistry;
        $this->slugger = $slugger;
    }

    
    #[Route('', name: '')]
    public function index() : Response{
        return $this->render('Project/project/index.html.twig');
    }

    #[Route('-detail/{slug}', name: '-detail')]
    public function detail(string $slug) : Response{
        $project = $this->projectRepository->findOneBy(['slug'=>$slug]);
        return $this->render('Project/project/detail.html.twig',[
            'project' => $project,
        ]);
    }

    #[Route('-admin', name: '-admin')]
    public function indexAdmin(Request $request): Response
    {
        $project = new Project();
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $slug = strtolower($this->slugger->slug($project->getCategory()->getName() . '-' . $project->getName()));

            if ($this->projectRepository->findOneBy(['slug' => $slug]) == null) {
                $project->setCreatedAt(new \DateTimeImmutable);
                $date = $form['started_at']->getData();
                $project->setStartedAt(DateTimeImmutable::createFromMutable($date) );
                $project->setSlug($slug);

                $this->addFlash('success', 'Projet ajouté');
                $manager = $this->managerRegistry->getManager();
                $manager->persist($project);
                $manager->flush();
            } else {
                $this->addFlash('warning', 'Projet déjà présent');
            }
        }

        return $this->render('Project/project/indexAdmin.html.twig', [
            'projects' => $this->projectRepository->findAll(),
            'form' => $form->createView(),
        ]);
    }

    #[Route('-admin/update/{id}', name: '-admin-update')]
    public function update(Request $request, Project $project): Response
    {
        $projetOld = clone $project;

        $form = $this->createForm(ProjectType::class, $project);        
        $form['started_at']->setData(DateTime::createFromImmutable($project->getStartedAt()));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $slug = strtolower($this->slugger->slug($project->getCategory()->getName() . '-' . $project->getName()));

            if ($projetOld->getSlug() == $slug) {
                $this->addFlash('success', 'Projet modifié');
                $manager = $this->managerRegistry->getManager();
                $manager->persist($project);
                $manager->flush();

                return $this->redirectToRoute('project-admin');

            } else {
                if ($this->projectRepository->findOneBy(['slug' => $slug]) == null) {
                    $project->setSlug($slug);
    
                    $this->addFlash('success', 'Projet modifié');
                    $manager = $this->managerRegistry->getManager();
                    $manager->persist($project);
                    $manager->flush();

                    return $this->redirectToRoute('project-admin');
                } else {
                    $this->addFlash('warning', 'Projet déjà présent');
                }
            }            
        }

        return $this->render('Project/project/formEdit.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    #[Route('-admin/delete/{id}', name: '-admin-delete')]
    public function delete(Project $project): Response
    {

        $this->addFlash('success', 'Projet retiré');
        $manager = $this->managerRegistry->getManager();
        $manager->remove($project);
        $manager->flush();

        return $this->redirectToRoute('project-admin');
    }
}

templates/Project/project/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detail project {{project.name}}{% endblock %}

{% block body %}
<main class="container">

    <div class="row justify-content-center">
        <h3 class="col-12 text-center text-color-orange">Fiche projet détaillée</h3>
    </div>

    {% include "_partials/brSmall.html.twig" %}

    <div class="row justify-content-center">
        <h3 class="col-12 text-center fs-2"><span class="badge bg-light p-2 text-color-blue">{{ project.name }}</span></h3>
        <p class="col-12 text-center fst-italic fs-4"><span class="badge bg-light p-2 text-color-blue">{{ project.shortText }}</span></p>
    </div>

    {% include "_partials/brSmall.html.twig" %}

    <div class="row row-cols-1 row-cols-lg-3 justify-content-center">
        <div class="col border-start border-end rounded border-light bg-color-green me-1 p-3">
            <h4>Type de projet : {{ project.category.name }}</h4>
            <h4>Environment principal : {{ project.environment }}</h4>
            <div class="container-fluid">
                <div class="row justify-content-evenly">
                    {% for skill in project.skill %}
                    <div class="col-1">
                        <img id="imgSkill" src="{{asset('img/skill/'~skill.image)}}"
                            alt="Logo de {{skill.name}}">
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col d-block d-lg-none my-2"></div>
        <div class="col border-start border-end rounded border-light bg-color-green p-3">
            <h5>{{project.shortText}}</h5>
            <p class="text-justify">{{project.description}}</p>
        </div>
    </div>

    {% include "_partials/brSmall.html.twig" %}

    <div class="row justify-content-center">
        <div class="col text-center border-start border-dark">
            <a class="text-light text-center" href="{{project.link}}">{{project.icon|raw}}</a>
            <p><span class="badge fs-4 bg-color-{{project.category.slug =='web-app' ? 'yellow' : cat.slug =='videogames' ? 'orange' : 'red'  }}">Cliquez pour découvrir</span></p>
        </div>
    </div>

    {% include "_partials/brSmall.html.twig" %}

    <div class="row justify-content-center">
        <div class="col-2">
            <a href="{{path('index')}}#project" class="btn btn-light fw-bold">Retour</a>
        </div>
    </div>

</main>
{% endblock %}

templates/Project/project/formEdit.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}Project - Update{% endblock %}

{% block body %}

<main class="container">

    <div class="row justify-content-center my-2">
        <h3 class="col-12 text-center text-capitalize">
            édition d'un projet
        </h3>
    </div>

    {% include "_partials/brSmall.html.twig" %}

    <div class="row justify-content-center">
        {{form_start(form)}}
        <div class="col-12">
            {{form_row(form.name,{'label':'Désignation :' })}}
            {{form_row(form.displayOnIndex, {'label':'Afficher sur accueil'})}}
            {{form_row(form.category, {'label':'Catégorie :'})}}
            {{form_row(form.started_at, {'label':'Débuté le :'})}}
            {{form_row(form.environment, {'label':'Environnement :'})}}
            {{form_row(form.shortText, {'label':'Description courte :'})}}
            {{form_row(form.description, {'label':'Description longue :'})}}
            {{form_row(form.link, {'label':'Lien vers :'})}}
            {{form_row(form.icon, {'label':'Icone :'})}}
            {{form_row(form.skill, {'label':'Compétences liées :'})}}
            {{form_row(form.submit, {'label':'Modifier'})}}
        </div>
        {{form_end(form)}}
    </div>

    {% include "_partials/brSmall.html.twig" %}

    <div class="row justify-content-end">
        <div class="col-1">
            <a href="{{ path('project-admin') }}" class="btn btn-secondary">Retour</a>
        </div>
    </div>
</main>

{% endblock %}

templates/Project/project/formModal.html.twig
<div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5 text-black" id="addModalLabel">Création d'un projet</h1>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>

			{{form_start(form)}}
			<div class="modal-body text-black">
				{{form_row(form.name,{'label':'Désignation :' })}}
				{{form_row(form.displayOnIndex, {'label':'Afficher sur accueil'})}}
				{{form_row(form.category, {'label':'Catégorie :'})}}
				{{form_row(form.started_at, {'label':'Débuté le :'})}}
				{{form_row(form.environment, {'label':'Environnement :'})}}
				{{form_row(form.shortText, {'label':'Description courte :'})}}
				{{form_row(form.description, {'label':'Description longue :'})}}
				{{form_row(form.link, {'label':'Lien vers :'})}}
				{{form_row(form.icon, {'label':'Icone :'})}}
				{{form_row(form.skill, {'label':'Compétences liées :'})}}
				{{form_row(form.submit, {'label':'Ajouter'})}}
			</div>
			{{form_end(form)}}

			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
			</div>

		</div>
	</div>
</div>

templates/Project/project/indexAdmin.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}Projects{% endblock %}

{% block body %}
<main class="container my-2">

    <div class="row justify-content-center">
        <div class="col-12">
            <h3 class="text-center">Les projets</h3>
        </div>
    </div>

    {% include "_partials/brSmall.html.twig" %}

    <div class="row justify-content-center">
        <div class="col-11">
            <table class="table table-light table-striped">
                <thead>
                    <th>Numéro</th>
                    <th>Nom</th>
                    <th>Catégorie</th>
                    <th>Résumé</th>
                    <th>Description</th>
                    <th>Outil</th>
                    <th>Débuté le</th>
                    <th>Actions</th>
                </thead>

                <tbody class="align-middle">
                    {% for project in projects %}
                    <tr>
                        <td>{{loop.index}}</td>
                        <td>{{project.name}}</td>
                        <td>{{project.category.name}}</td>
                        <td>{{project.shortText}}</td>
                        <td>{{project.description|u.truncate(15,'...',false)}}</td>
                        <td>{{project.environment}}</td>
                        <td>{{project.startedAt|date('d/m/Y')}}</td>

                        <td>
                            <a href="{{ path('project-admin-update',{'id':project.id}) }}" class="btn btn-info"><i class="bi bi-recycle fs-5"></i></a>
                            <a href="{{ path('project-admin-delete',{'id':project.id}) }}" class="btn btn-danger"><i class="bi bi-trash fs-5"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% include "_partials/brSmall.html.twig" %}

    <div class="col-12 text-end">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
            data-bs-target="#addModal">Création</button>
    </div>

</main>

{% include "Project/project/formModal.html.twig" %}

{% endblock %}